### ISSUE TITLE
Feature request: Option for automatic off only

### ISSUE THREAD

**Issue by sjthespian** [jseidl/hass-magic_areas#108]
I have quite a few lights in the house where I currently have timers that turn the lights off if there is no one in the room. I have no interest in automatically turning them on when someone enters the room, but I would like to be able to turn them off after a period of time if someone "forgets" to.

I'm not sure if the best way to do this would be to have separate `control_lights` and `control_lights_off` features, or if there should be `main_lights` and `main_lights_off` config options. I like the latter gives more flexibility, but it would also require that there be an option for "None" in `main_lights` instead of the current default of "all".

Having the ability to just turn lights off when the presence detector goes off would let me retire quite a bit of manual code I have running in my ISY.

**Comment by danielbrunt57** [comment]
After re-reading [synapselabs.io posts bring homeassistant areas to life with magic areas](https://synapselabs.io/posts/bring-home-assistant-area-to-life-with-magic-areas/) and doing some testing here, I believe the existing integration will work for your needs...

> Magic Areas will automatically turn off all light, climate and media_player entities in that area when presence is changed to off. This ensures you’ll never let anything running when the room is not being used.

> On disable state, Magic Areas won’t turn any lights on, but will still turn them off if the area presence state goes to off.

The area **will** turn off area lights whenever presence is cleared regardless whether night: is true or false.
As long as night: is never true, it will not turn on the lights when presence is detected.  
So just specify a valid entity ID to disable automatic light control [night_entity] and set its `Entity state to disable automatic light control` to a value that will never be true.  I.e. rather than `on`|`off` enter something like `never`.
Or use a new entity that you may never set to on and specify its state for true as `on`.
As long as the state of the night_entity never matches the specified state string, automatic lighting will never turn the lights on but will turn them off when presence is cleared.

**Comment by jseidl** [comment]
@sjthespian did Daniel's response worked?

**Comment by sjthespian** [comment]
I haven't had any time lately to dig into this, work has been a nightmare... I'm hoping to spend some time on it this weekend.

**Comment by sjthespian** [comment]
I need to run a couple more tests, but I think this is going to work. I have it reliably turning lights off in my home office, I just need to make sure that isn't turning them on after dark tonight.

**Comment by jseidl** [comment]
Let me know so I can close this

**Comment by sjthespian** [comment]
This does work, I have disabled my old programs that turn off the lights after a period of time and am now using Magic Areas to do that. Nice work on this module! The only drawback to this method is that I can't use "sleep" lights, as they never trigger since the area never has "night" set to true.
