### ISSUE TITLE
Area doesn't clear, but no sensor is active

### ISSUE THREAD

**Issue by Patrick1610** [jseidl/hass-magic_areas#119]
I have a 'main floor' area which is occupied with 4 rooms (they are set by placing those entities in the 'main floor' area, like this: 
![Screenshot 2021-05-08 at 21 09 18](https://user-images.githubusercontent.com/6585375/117550660-c9352c00-b041-11eb-8953-2c0e8a7009da.png)
Now the 'main floor' area remains active, even though the 4 rooms that fill this area are not occupied. 
<img width="401" alt="Screenshot 2021-05-08 at 21 10 55" src="https://user-images.githubusercontent.com/6585375/117550713-ff72ab80-b041-11eb-8c80-e430173f4432.png">
The 'main floor' does see that there are no active sensors, but does not clear the area. 
Any ideas what I could try? 
I've removed the entities from the area and re-added them, restarted and tried a couple of different settings (clearout, excluding).

**Comment by jseidl** [comment]
I'm not sure if this area nesting will work since when Magic Areas start, when it's setting up Main Floor there's no guarantee that Living Room will be set up first and it will fail to monitor this entity. MA is not designed to support area nesting and this will probably not work.

You could try as an workaround, set up a template sensor based on `binary_sensor.living_room` and add this template sensor to main floor. This will make the template sensor be `unknown` while booting up but will probably pick up the value when everything is set up

**Comment by Patrick1610** [comment]
Thanks! I thought that would have worked, since there is an 'interior' and 'exterior' as well. 
You thoughts have helped though, I just made a group of the 4 binary sensors from the areas on the main floor. 
When the 4th becomes inactive (state 'off'), the group has the same state.
