### ISSUE TITLE
Feature request: Add config flow

### ISSUE THREAD

**Issue by KTibow** [jseidl/hass-magic_areas#16]
It'd be nice to use the GUI to set up this integration.

**Comment by jseidl** [comment]
Would be a great addition, although I've never implemented `config_flow` so it might take a while for this feature to come out.

**Comment by jseidl** [comment]
It's finally coming on 2.0.0!

![image](https://user-images.githubusercontent.com/283041/105627096-6f3d8d00-5de9-11eb-8a57-8d7d22fb666c.png)

![image](https://user-images.githubusercontent.com/283041/105627103-76fd3180-5de9-11eb-85ef-e16b6b270e07.png)

YAML will still be supported but the syntax changed in order to support `config_flow`

**Comment by TheArcturian** [comment]
Very nice! This should make it available to a lot more (new) Home Assistant users.

**Comment by danielbrunt57** [comment]
Does this mean we won't have to restart HA to reload MA?

**Comment by jseidl** [comment]
Yeap, just change the config on the UI and it should reload

**Comment by jseidl** [comment]
Closed by #74
