### ISSUE TITLE
Bug: light group secondary states - entity restricted to a single state for activation

### ISSUE THREAD

**Issue by maxfield-allison** [jseidl/hass-magic_areas#253]
**Describe the bug**
Previous versions of MA allowed for the use of pipes "|" to include more than one state to be evaluated for dark, task, accent etc. lights. 
**To Reproduce**
Create an area configuration with light groups,
Assign an entity with multiple states, e.g. media player, to one of the light groups 
Assign multiple states separated by pipes 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/42394355/183539499-41086708-4498-4c94-b8e6-7e0f52ffe1d1.png">

**Expected behavior**
the accent state should be applied to an area with any of the accent entity states active

**Additional context**
I updated from one of the 3.0 betas and noticed this behavior. I wiped and reconfigured MA but the issue persists.

**Comment by jseidl** [comment]
> Previous versions of MA allowed for the use of pipes "|" 

That wasn't intentional. That was probably side-effect of some internal Home Assistant logic/expansion that I'm not aware.

Solution for your case would involve using a template binary sensor. You can open a [feature request](https://github.com/jseidl/hass-magic_areas/discussions/categories/ideas-feature-requests) for this if you'd like.
