### ISSUE TITLE
Bug: Accent lights come on during sleep mode and during the day

### ISSUE THREAD

**Issue by sjthespian** [jseidl/hass-magic_areas#260]
**Describe the bug**
I have a room where I have the ceiling lights configured to shut off after a set period of time, but not to come on on motion. I have also configured an accent light for that room. In this configuration, the accent light is coming on on any motion, during both the night and day.

**To Reproduce**
1. Configure an area with both ceiling lights and an accent light.
2. Remove all settings from "States which overhead lights are turned on", set a sleep light to "sleep", and set an accent light to come on in the "occupied" state.
3. Set the room into sleep mode, wait for presence to clear, and active a motion sensor.
4. The accent light should come on

**Expected behavior**
I would expect the accent light to come on only at night and when the room is occupied.

**Screenshots**
<img width="379" alt="Screen Shot 2022-10-03 at 10 58 15" src="https://user-images.githubusercontent.com/1789285/193646405-6041c44e-fb6e-4015-acf2-ac037958db38.png">
<img width="370" alt="Screen Shot 2022-10-03 at 10 58 26" src="https://user-images.githubusercontent.com/1789285/193646422-64513677-d0a2-4833-8f80-60c5e9807069.png">

You can also find a pastbin of the json version of this configuration at https://pastebin.com/edit/6kbz6khN. This was extracted from the .storage/core.config.entries file with `jq '.data.entries[] | select(.domain == "magic_areas") | select(.data.name == "Great Room")' .storage/core.config_entries`

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser Chrome
 - Version 105.0.5195.125

**Comment by jseidl** [comment]
Just to confirm, the expected behavior is

1. Only the accent lights come on at night, when entering the room but not when sleep mode is on
2. Sleep lights should come on when sleep mode is on, at night also

Is that correct?

One thing I've noticed is that your sleep lights isn't set to come up on `occupancy` which might be why is not being triggered when you walk into the room on sleep mode (and might be falling back to the configured one, accents)

Can you check if that area has a dark state during the day? Lights should never come on without that state

**Comment by jseidl** [comment]
Closing due inactivity, please reopen if you still have this issue.
