### ISSUE TITLE
Bug: Lights are turned off if area is occupied and dark mode switches to off

### ISSUE THREAD

**Issue by klatka** [jseidl/hass-magic_areas#264]
**Describe the bug**
Lights are turned off if area is occupied and dark mode is changing to off despite wiki says there should be no operation:
<html>
<body>
<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Dark state behavior matrix</h3>

Area State | Dark state set | Dark state | Lights
-- | -- | -- | --
occupied | no | n/a | turn on
occupied | yes | off | no-op => actually turn off
occupied | yes | on | turn on
clear | no | n/a | turn off
clear | yes | off | turn off
clear | yes | on | turn off

</body>
</html>

Magic Areas version 3.0.1

**Comment by jseidl** [comment]
The wiki is wrong. Area becoming bright SHOULD turn off lights, maybe this can be an option in the future but that's the intended behavior, sorry about the wiki, will fix that

**Comment by jseidl** [comment]
Actually that box only says if you have a dark entity set and it's off when you enter the room, it should do nothing (because it's bright already). I'm gonna remove that box until I can make a better one to avoid this confusion

**Comment by jseidl** [comment]
Also, if you still want this feature please submit a feature request, should be easy to implement

**Comment by krohrsb** [comment]
I have this issue. An example:

I have a front porch with a camera and overhead lights.

The camera has a "is dark" sensor.

If I use the is dark sensor, when the area is occupied and it is dark the lights turn on -- great. However when the lights turn on the "is dark" turns off, which tells magic to turn the lights off, apparently.

Seems the issue is -- this is applying all the time instead of only when changing occupied states?

The result is, at night, the lights will just keep flip flopping. Seems like not intended behavior. Unless I'm using it wrong.

**Comment by jseidl** [comment]
@krohrsb If your `is_dark` is based on illuminance then it will not work with Magic Areas as you will be stuck on a loop where lights turn on because it's dark but it isn't dark anymore so MA tells the lights to turn off and so on.

You can set some light groups to only react to occupancy changes but not state changes, and that should mostly solve your immediate problem but I do recommend using the `sun` sensor or the aggregate `binary_sensor.exterior_light` (if you're using the aggregates feature) sensor which is less sensitive to change in a single sensor (assuming you have multiple light sensors outside)

**Comment by krohrsb** [comment]
Interesting. I feel my use case is still valid. Should I make a feature request?

Like, it may be light outside but still dark in the room I am entering. It's occupied and dark turn the light on. 

More accurately changing from clear to occupied should be the only time is dark is checked (or at least have this as an option to facilitate this case?)

**Comment by krohrsb** [comment]
Though let me also try your suggestion if occupancy and not state

**Comment by krohrsb** [comment]
Hmm, let me know if i need to move this into a discussion.

I tried removing "state" from "When should overhead lights be controlled?" (the group I have my light in).

But when the lights come on, and turn things bright, it switches the lights back off still. Unless you were referring to a different area of the configuration?

Perhaps I am not aware of specifically the area you are talking about in

> You can set some light groups to only react to occupancy changes but not state changes, and that should mostly solve your immediate problem

**Comment by jseidl** [comment]
> Interesting. I feel my use case is still valid. Should I make a feature request?
Sure, the feature requests are in the discussions area, feel free to open one!

> Like, it may be light outside but still dark in the room I am entering. It's occupied and dark turn the light on.
Absolutely, that's why I use 3 different exterior illuminance sensors for it. Their values are averaged using the "Aggregate Sensors" feature and then I create a template binary sensor that if that value is below a given threshold that is too dark inside, then it's off, and use this sensor as my dark sensor (in reverse).

 > More accurately changing from clear to occupied should be the only time is dark is checked (or at least have this as an option to facilitate this case?)

That indeed is currently not supported, but open a feature request for that. Bear in mind if the light from the camera is already on and the room gets occupied, no lights will turn on and will stay off until the room is clear again. That means if the camera light goes to off again, you'll be in darkness.

The current behavior is not a bug, it's meant to work as if you're in a room and it gets dark outside, lights come on automatically and if you're in a room with lights on and sun rises, the lights will be turned off because the room is probably already bright from the sun.

With the feature you're requesting, when you're in a room for a while and it gets dark, you'll have to turn your lights by hand like a savage :)
